import Head from "next/head";
import { BsFillMoonStarsFill, BsGithub } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../../public/dev-ed-wave.png";
import design from "../../public/design.png"
import code from "../../public/code.png"
import consulting from "../../public/consulting.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bobby&#39;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          {/* Navigation */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="flex text-xl font-burtons">
              <BsGithub />
              <a href="https://www.github.com/bobbyzto">/bobbyzto</a>
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* Home Page */}
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Robert Weche
            </h2>
            <h3 className="text-2xl py-2">Developer and designer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Freelancer providing services for programming and design content
              needs. Join me down below and let&#39;s work together!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>

          {/* 3d image */}
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} alt={"deved"} fill={true} objectFit="cover" />
          </div>
        </section>

        {/*  */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet. Qui porro pariatur qui commodi
              aspernatur qui amet <span className="text-teal-500">quaerat</span>{" "}
              et repellat culpa. Ut asperiores similique et aliquid asperiores
              qui inventore voluptatem!
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet. Qui porro pariatur qui commodi
              aspernatur qui amet <span className="text-teal-500">quaerat</span>{" "}
              et repellat culpa. Ut asperiores similique et aliquid asperiores
              qui inventore voluptatem!
            </p>
          </div>
          <div>
            <div>
              <Image src={design} width={100} height={100} alt={"card"} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Blender</p>
              <p className="text-gray-800 py-1">Three.js</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
